### PR TITLE
WIP Azure Pipelines trigger (forked)

### PR DESCRIPTION
**Pull request by davidzwa**
Fork and own work on other PR by sloria

### CODE REVIEW

**Comment by davidzwa** [comment]
So I find the templates given in which refer to [job--python-tox](https://github.com/sloria/azure-pipeline-templates/blob/sloria/job--python-tox.yml) quite complex and I notice there is no step to just simply 'install dependencies', which the base `pytest-azure-pipelines` does automatically.

I see no issue in just using the `azure pytest` basic template? We can use `pytest-lint` and something else for the docs. We'd need to find a way to export the coverage and test output artifact, if you are in need of that info.

You should hook up Pypi service when you feel ready for it as it requires editing the Azure project.

**Comment by davidzwa** [comment]
@sloria it'd be great to hear your thoughts!

**Comment by sloria** [comment]
Sorry haven't had a chance to look yet... it'd be great if this could be put in line with the other marshmallow-code repos, i.e. use the same templates.

The idea with the tox jobs is that they use `tox` to create an virtualenv and install dependencies, rather than installing in the "global" virtual environment. This is very convenient for reproducing issues locally.

**Comment by davidzwa** [comment]
The tox template fails (I tried) because it misses installing the dependencies of `requirements.txt`. So I'd need to extend the template, or you'd need to add it to your repo.

I will do the extension, although I am new to it. Nice to learn.

**Comment by sloria** [comment]
Rather than modify the AP templates, I think the better approach is to bring this project in line with the rest of marshmallow-code, i.e. use `setup.py` instead of `requirements.txt`. 

Example: https://github.com/marshmallow-code/flask-marshmallow/blob/dev/setup.py#L6-L22

This allows each tox environment to only install the minimum necessary requirements. Note: you'll also need to update `tox.ini`.

**Comment by davidzwa** [comment]
I've recovered my energy to work and will look at this tomorrow evening.

**Pull request closed without merging**
