### PR TITLE
Fix TypeError when calling get_attribute

### LINKED ISSUE #6: get_attribute() takes exactly 2 arguments (4 given)
I am getting this error. Is it me doing something wrong or is it a bug. The problem seems to be happening because its using the get_attribute method in Field class of rest_framework and not the one defined in
BaseSchema class of Marshmallow.

### PR DESCRIPTION
**Pull request by sloria**
Ensure marshmallow's get_attribute is used
closes #6

### CODE REVIEW

**Comment by sloria** [comment]
Simplified to a 1-line fix. Let me know if there's anything else to be done before this is merged.

**Comment by sloria** [comment]
Also fixed compatibility with marshmallow 1.x. Tests finally passing.

**Comment by matheusho** [comment]
@tomchristie I have the same problem. Please, merge it =)

**Comment by lovelydinosaur** [comment]
If anyone's willing to take ownership of the project I'll happily hand it over?

**Comment by sloria** [comment]
I can't promise I can invest as much time as this project needs, but I'd be glad to review and merge PRs as they come.

**Comment by lovelydinosaur** [comment]
@sloria - Do you have a PyPI account - if so what's your username there?

**Comment by sloria** [comment]
My PyPI username is sloria.

**Comment by lovelydinosaur** [comment]
@sloria - I've added you as a maintainer on GitHub and PyPI.

Use the `./setup.py publish` command to push new releases, making sure to have first incremented the version number. Once that runs it'll also prompt you to tag the release.

Let me know if you run into any issues.

**Comment by sloria** [comment]
Thanks! I'll working on getting a release out this weekend.

**Comment by lovelydinosaur** [comment]
Fab :)

**Pull request merged**
